-- MySQL Script generated by MySQL Workbench
-- Tue 25 Jul 2017 07:19:04 PM EAT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema harlerte_mkopopopote
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema harlerte_mkopopopote
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `harlerte_mkopopopote` DEFAULT CHARACTER SET utf8 ;
USE `harlerte_mkopopopote` ;

-- -----------------------------------------------------
-- Table `harlerte_mkopopopote`.`tblUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harlerte_mkopopopote`.`tblUser` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idno` VARCHAR(10) NULL,
  `lastname` VARCHAR(100) NULL,
  `firstname` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `dob` DATE NULL,
  `gender` VARCHAR(7) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `harlerte_mkopopopote`.`tblPhone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harlerte_mkopopopote`.`tblPhone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imei` VARCHAR(20) NULL,
  `telno` VARCHAR(13) NULL,
  `password` VARCHAR(128) NULL,
  `tbluser_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tblphone_tbluser_idx` (`tbluser_id` ASC),
  CONSTRAINT `fk_tblphone_tbluser`
    FOREIGN KEY (`tbluser_id`)
    REFERENCES `harlerte_mkopopopote`.`tblUser` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `harlerte_mkopopopote`.`tblLoanLimit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harlerte_mkopopopote`.`tblLoanLimit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `limit` DOUBLE NULL,
  `tblPhone_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tblLoanLimit_tblPhone1_idx` (`tblPhone_id` ASC),
  CONSTRAINT `fk_tblLoanLimit_tblPhone1`
    FOREIGN KEY (`tblPhone_id`)
    REFERENCES `harlerte_mkopopopote`.`tblPhone` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `harlerte_mkopopopote`.`tblLoanStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harlerte_mkopopopote`.`tblLoanStatus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `loanstatus` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `harlerte_mkopopopote`.`tblLoan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harlerte_mkopopopote`.`tblLoan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `startdate` DATE NULL,
  `duedate` DATE NULL,
  `loanamount` DOUBLE NULL,
  `interestrate` DECIMAL NULL,
  `loanpaymentamount` DOUBLE NULL,
  `tblLoanStatus_id` INT NOT NULL,
  `tblPhone_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tblLoan_tblLoanStatus1_idx` (`tblLoanStatus_id` ASC),
  INDEX `fk_tblLoan_tblPhone1_idx` (`tblPhone_id` ASC),
  CONSTRAINT `fk_tblLoan_tblLoanStatus1`
    FOREIGN KEY (`tblLoanStatus_id`)
    REFERENCES `harlerte_mkopopopote`.`tblLoanStatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblLoan_tblPhone1`
    FOREIGN KEY (`tblPhone_id`)
    REFERENCES `harlerte_mkopopopote`.`tblPhone` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `harlerte_mkopopopote`.`tblPayments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harlerte_mkopopopote`.`tblPayments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL NULL,
  `date` VARCHAR(45) NULL,
  `tblLoan_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tblPayments_tblLoan1_idx` (`tblLoan_id` ASC),
  CONSTRAINT `fk_tblPayments_tblLoan1`
    FOREIGN KEY (`tblLoan_id`)
    REFERENCES `harlerte_mkopopopote`.`tblLoan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
