-- MySQL Script generated by MySQL Workbench
-- Mon 24 Jul 2017 04:54:38 PM EAT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema harlerte_mkopopopote
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema harlerte_mkopopopote
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `harlerte_mkopopopote` DEFAULT CHARACTER SET utf8 ;
USE `harlerte_mkopopopote` ;

-- -----------------------------------------------------
-- Table `harlerte_mkopopopote`.`tblUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harlerte_mkopopopote`.`tblUser` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idno` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `dob` DATE NULL,
  `gender` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
